### ISSUE TITLE
[Proposal] New/Updated Schema for Question Catalogue

### ISSUE THREAD

**Issue by timonf** [certificationy/certificationy#92]
The current schema:
- does not have identifiers (it's hard to synchronize questions with a database!)
- does not support versioning (mentioned in certificationy/symfony-pack#51)
- supports a help column in questions, but is never used in certificationy/symfony-pack or certificationy/php-pack
- supports `yml` (without `a`) file extension (not used by Symfony 4 anymore)

So I want introduce my proposal for an updated schema:
- `id` (just random generated uuid), so we can identify updated questions easily
- `version` should work similar to composer requirements (`symfony: "^2.3"` for Symfony 2.3 to 2.8)
- `question` field should contain text or inline YAML (so we can highlight code blocks easier, if we want to show questions in a browser); YAML is also easy readable for humans :)
- we should use the help field! (would be also easier to review contributions, as I discovered the process thing from the `symfony3.yml` works also in Symfony 2.3!)
- we should rename files to yaml to have a familiar feeling with Symfony 4

This is what an updated YAML file could look like:

```yaml
# components.yaml (instead of symfony3.yml in certificationy/symfony-pack)
category: Various Symfony Components
questions:
    -
        id: 'ded068d9-e76e-415a-995c-2a26e9c73f9f'
        question: 'What is the default signal sent by Process component to stop a process?'
        versions:
            symfony: '^2.3|~3.0|~4.0'
        help: |
            https://en.wikipedia.org/wiki/Signal_(IPC)
            https://symfony.com/doc/2.3/components/process.html#stopping-a-process
            https://github.com/symfony/process/blob/2.3/Process.php#L636
        answers:
            - {value: 'SIGINT',        correct: false}
            - {value: 'SIGKILL',       correct: true}
            - {value: 'Process::STOP', correct: false}
            - {value: '9',             correct: true}
    -
        id: 'ebc9ed55-dcb0-46eb-9003-d135b57b4e95'
        question: |
            What can be placed in `?????` to be valid?

                use Symfony\Component\Yaml\Yaml;

                $value = Yaml::parse(?????);
        versions:
            symfony: '^2.2'
        help: |
            https://symfony.com/doc/2.3/components/yaml/introduction.html#reading-yaml-files
            https://github.com/symfony/yaml/blob/2.3/Yaml.php#L44
        answers:
            - {value: '"/path/to/file.yml"',                    correct: false}
            - {value: 'file_get_contents("/path/to/file.yml")', correct: false}
            - {value: 'Both are valid',                         correct: true}
    -
        id: '7e89f317-dd3c-487b-9bd2-ff700e1d0d4a'
        question: |
            What can be placed in `?????` to be valid?

                use Symfony\Component\Yaml\Yaml;

                $value = Yaml::parse(?????);
        versions:
            symfony: '~3.0|~4.0'
        help: |
            https://symfony.com/doc/3.0/components/yaml.html#reading-yaml-files
            https://github.com/symfony/yaml/blob/3.0/Yaml.php#L41
            https://github.com/symfony/yaml/blob/3.0/Parser.php#L60
        answers:
            - {value: '"/path/to/file.yml"',                    correct: false}
            - {value: 'file_get_contents("/path/to/file.yml")', correct: true}
            - {value: 'Both are valid',                         correct: false}
```

Things to discuss:
- yey or ney?
- versions? → composer package names (or just some aliases like `php`, `symfony`, `twig`, `doctrine` etc.)
- how can versions be filtered later (arguments in cli, or configuration)?
- update this library to support versions and ids? (maybe generate a random fallback id, if id is not provided by given YAML file)
